version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: taskmaster_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TaskMaster
    volumes:
      - taskmaster_pg_data:/bitnami/postgresql

volumes:
  taskmaster_pg_data:
    driver: local
